BOOST_1=../../boost_1_51_0
QUANTLIB_H_1=../../QuantLib-1.4
QUANTLIB_LIB_1=../../ql-1.4

BOOST_2=../$(BOOST_1)
QUANTLIB_H_2=../$(QUANTLIB_H_1)
QUANTLIB_LIB_2=../$(QUANTLIB_LIB_1)

BOOST=$(BOOST_$(DIR_LEVEL))
QUANTLIB_H=$(QUANTLIB_H_$(DIR_LEVEL))
QUANTLIB_LIB=$(QUANTLIB_LIB_$(DIR_LEVEL))
EXT=.exe
