
macros.exe: 01-macros.cpp
	g++ -I..\..\boost_1_51_0 $< -o $@

sharedptr.exe: 02-sharedptr.cpp
	g++ -I..\..\boost_1_51_0 $< -o $@

sharedptr-ex.exe: 02-sharedptr-ex.cpp
	g++ -I..\..\boost_1_51_0 $< -o $@

distribution.exe: 03-distribution.cpp
	g++ -I..\..\boost_1_51_0 $< -o $@

randnum.exe: 04-randnum.cpp
	g++ -I..\..\boost_1_51_0 $< -o $@

randnum-ex.exe: 04-randnum-ex.cpp
	g++ -I..\..\boost_1_51_0 $< -o $@

clean:
	rm -f *.exe
